imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: @ecloreuserBundle/Resources/config/services.yml }
    
spy_timeline:
    paginator: ~
    drivers:
        orm:
            object_manager: doctrine.orm.entity_manager
            classes:
                query_builder: ~ # Spy\TimelineBundle\Driver\ORM\QueryBuilder\QueryBuilder
                timeline:  eclore\userBundle\Entity\Timeline
                action:    eclore\userBundle\Entity\Action
                component: eclore\userBundle\Entity\Component
                action_component: eclore\userBundle\Entity\ActionComponent       
    filters:
        data_hydrator:
            priority:             20
            service:              spy_timeline.filter.data_hydrator
            filter_unresolved:    false
            locators:
                - spy_timeline.filter.data_hydrator.locator.doctrine_orm
        duplicate_key: ~     
    spread:
        on_subject: true         # DEFAULT IS TRUE  Spread each action on subject too
        on_global_context: true   # Spread automatically on global context
        deployer: spy_timeline.spread.deployer.default
        delivery: immediate
    render:
        path:     'ecloreuserBundle:Timeline/verbs'
        

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:
        enabled: true
        api: 2.4
        enable_annotations: true 
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    read_from: "%kernel.root_dir%/../www"
    bundles:        [ecloreuserBundle]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar"
        #yui_js:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
    disable_delivery:  true
    
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: eclore\userBundle\Entity\User
    service:
        mailer: fos_user.mailer.twig_swift
        user_provider : fos_user.user_provider.username
    from_email:
            address:        contact@reseau-eclore.org
            sender_name:    "RÃ©seau Eclore"
    profile:
        form:
            type: eclore_user_profile
    registration:
        form:
            type: eclore_user_registration
        confirmation:
            enabled:    false
            template: ecloreuserBundle:Registration:email.html.twig
    resetting:
        token_ttl: 86400
        email:
            template:   ecloreuserBundle:Resetting:email.html.twig
                       
#Sonata Block Bundle
sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]
        sonata.block.service.text: ~
        sonata.block.service.action: ~
        sonata.block.service.rss: ~
        sonata.block.service.overview: ~

sonata_admin:
    title: "Plateforme de gestion des enregistrements"
    #title_logo: ~
    dashboard:
        blocks:
        
            # display a dashboard block
            - { position: left, type: sonata.admin.block.admin_list }
            - { position: right, type: sonata.block.service.overview }   
        
