security:
    encoders:
        Symfony\Component\Security\Core\User\User: sha512
        eclore\userBundle\Entity\User: sha512
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_USER:        [ROLE_USER]
        ROLE_TBC:           [ROLE_USER]
        ROLE_YOUNG:       [ROLE_YOUNG, ROLE_USER]
        ROLE_ASSOM:        [ROLE_ASSOM, ROLE_USER]
        ROLE_INSTM:        [ROLE_INSTM, ROLE_USER]
        ROLE_ADMIN:       [ROLE_YOUNG, ROLE_ASSOM, ROLE_INSTM]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
        main:
            pattern:   ^/
            anonymous: true
            provider:  fos_userbundle
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
            logout:
                path:   fos_user_security_logout
                target: /
            remember_me:
                key:      123er1e2
                lifetime: 3600
                path:     /
                domain:   ~
            switch_user: { role: ROLE_USER, parameter: _user }

    access_control:
        - { path: ^/home, roles: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/association, roles: ROLE_ASSOM }
        - { path: ^/jeune, roles: ROLE_YOUNG }
        - { path: ^/institution, roles: ROLE_INSTM }
        #- { path: ^/admin, roles: ROLE_ADMIN }
        #- { path: ^/admin/console, roles: ROLE_SUPER_ADMIN }